sudo: required
services:
  - docker

before_install:
  - docker build -t thesan4es/docker-react -f Dockerfile.dev .

script:
  - docker run thesan4es/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "alexz-docker"
  env: "AlexzDocker-env"
  bucket_name: elasticbeanstalk-us-east-1-988585708477
  bucket_path: "alexz-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
